### ISSUE TITLE
Nuxt3 환경에서 plugin 적용에 대하여

### ISSUE THREAD

**Issue by codma1123** [Dongkyuuuu/vue3-naver-maps#18]
vite + nuxt3 + typescript 환경에서 플러그인을 적용하려 합니다.

```
import naver from "vue3-naver-maps"

export default defineNuxtPlugin(nuxtApp => {
  nuxtApp.vueApp.use(naver, {
    clientId: import.meta.env.VITE_CLIENT_ID,
    category: "ncp", 
    subModules: "" 
  })
})
```

먼저, use() 메소드에서 naver가 플러그인이 아니라는 오류가 발생하며,
naver를 any로 캐스팅하여 구문오류를 없앤 후, 실행해보아도 

콘솔에서는 
A plugin must either be a function or an object with an "install" function. 에러와, 

브라우저에서는
ntaxError: The requested module '/_nuxt/node_modules/vue3-naver-maps/dist/vue3-naver-maps.esm.js?v=' does not provide an export named 'default'

오류가 발생합니다.

![image](https://user-images.githubusercontent.com/82079706/235336002-6a2e9fda-25ae-4005-b62a-7a81039f6f45.png)

package.json은 다음과 같습니다.

**Comment by codma1123** [comment]
다음과 같은 방법으로 해결했습니다. 
1. naver -> createNaverMap,
2. use의 두번째 인자 옵션을 any로 캐스팅

**Comment by Dongkyuuuu** [comment]
안녕하세요! 제보 감사합니다.

확인해보았는데 [vue3-naver-maps Nuxt 문서](https://dongkyuuuu.github.io/vue3-naver-maps/start/nuxt.html)에 `4.1.0`업데이트 이후 문서 업데이트가 안되어있었네요 😅
지금 업데이트 되었으니, 문서 다시 확인해주시면 되겠습니다!

```ts
import { createNaverMap } from "vue3-naver-maps";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(createNaverMap, {
    clientId: "c4ovrqy4fg",
    category: "ncp", // ncp 사용하시는 경우 필드 제거해주셔도 기본값으로 ncp 적용됩니다
    subModules: [] // string이 아닌 Array 이고, 사용 안해주시는 경우 필드 제거해주셔도 됩니다
  });
});

```
