### ISSUE TITLE
libraries 지원 여부

### ISSUE THREAD

**Issue by zepinos** [DongKyuuuu/vue3-naver-maps#6]
안녕하세요.

Geocode, ReverseGeocode 을 지원하나요? vue-naver-maps 에서는 main.js 에 libraries 로 geocoder 을 추가해서 사용할 수 있던데, vue3-naver-maps 에서는 지원하는지 궁금합니다.

**Comment by zepinos** [comment]
죄송합니다. libraries 가 아니라 subModules 군요. vue-naver-maps 문서를 잘못 읽었습니다.

**Comment by DongKyuuuu** [comment]
현재 서브모듈 지원하고 있습니다! [SubModules](https://dongkyuuuu.github.io/vue3-naver-maps/api/#submodules)에서 확인 가능합니다
