### ISSUE TITLE
위성지도 지원 여부

### ISSUE THREAD

**Issue by jieun94** [Dongkyuuuu/vue3-naver-maps#7]
mapTypeControl: true
설정을 해도 일반 지도만 나오는데 위성지도는 지원 안하는건가요?

**Comment by Dongkyuuuu** [comment]
`mapTypeControl`이 아닌 `mapTypeId`를 통해 지도 타입 변경이 가능합니다.
다만 현재 `normal` 타입만 지원하고 있습니다. 해당 옵션 추가 업데이트 이후 다시 말씀드리도록 하겠습니다.

**Comment by Dongkyuuuu** [comment]
`3.2.1` 버전으로 맵 타입 사용 가능합니다
